# Generated by Django 2.0.1 on 2018-12-05 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Developer', 'Developer')], max_length=50)),
                ('mobile_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter Valid Mobile Number', regex='^[6-9]\\d{9}$')])),
            ],
        ),
    ]
