# Generated by Django 2.0.1 on 2018-12-05 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='user',
        ),
    ]
