# Generated by Django 2.0.1 on 2018-12-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='deleted_at',
            field=models.DateTimeField(default=None),
        ),
    ]
