# Generated by Django 2.0.1 on 2018-12-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20181205_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='created_by',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='deleted_by',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
