# Generated by Django 2.0.1 on 2018-12-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20181205_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='updated_by',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
